import type { Metadata } from "next";
import { Noto_Sans_JP, Bruno_Ace_SC } from "next/font/google";
import "./globals.css";

const notoSansJP = Noto_Sans_JP({
	subsets: ["latin"],
	variable: "--font-noto-sans-jp",
});

const brunoAce = Bruno_Ace_SC({
	subsets: ["latin"],
	variable: "--font-bruno-ace-sc",
	weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSansJP.variable} ${brunoAce.variable}`}>
        {children}
      </body>
    </html>
  );
}
